### ISSUE TITLE
Monitor and update JJWT when possible

### ISSUE THREAD

**Issue by rkuijt** [arothuis-hu/hu-land-casino#15]
There have been some nice overall changes to the JJWT library that is being used in this project.

We're currently doing a lot of low-level work for signing and verifying SJWT's.
Their GitHub repo shows a lot of updates which include builders and helpers and generally make the code a lot easier to understand.
I think this would help our students as well.

It would also mitigate the use of `this.secret.bytes[]`, which is a nice bonus.

https://github.com/jwtk/jjwt

**Comment by ghost** [comment]
Laten we hier binnenkort naar kijken! Blij dat er builders etc zijn bijgekomen

**Comment by ghost** [comment]
https://github.com/jwtk/jjwt/releases/tag/0.12.0 lijkt erop dat sinds deze release (+ nieuwere versies ofc) de support er is

**Comment by TomKemperNL** [comment]
Ik zie dit net, en de nieuwere docs lijken best veel op wat we al doen in de applicatie.

Mis ik iets, of is dit ergens het afgelopen jaar al gedaan?

Dus wat is er concreet mis met de oude versie?

**Comment by TomKemperNL** [comment]
Nevermind, changes gezien, want ineens was van alles deprecated. Maar eerlijk gezegd vind ik het maar een klein verschil.
