### ISSUE TITLE
does it admin admin?

### ISSUE THREAD

**Issue by Josvanreenen** [arothuis-hu/hu-land-casino#18]
"This creates an admin user with the username and password `admin` and `admin`"
Not that it actually matters, but does it? 

It would seem that the register request from the postman collection does this, not the command "docker-compose up"

https://github.com/huictstaff/bep2-huland-casino/blob/0ef603a7fdf70312c1488b3f9feb8bd0ed671ace/README.md?plain=1#L77C1-L78C12

**Comment by TomKemperNL** [comment]
Yep, het admin-admint :)

De postman-post admin-admint omdat ie in de User-tabel van de database een user aanmaakt met admin/admin.
De docker-compose maakt een postgres-database aan, met als postgres-account (dus niet de user tabel) admin/admin.

Kortom:
* docker compose admin-admint een db-user
* Postman-post admin-admint een user-user

Helder toch?:)


(...en we vragen ons af waarom we soms niet serieus genomen worden?)
